export const POST_BUSY = 'POST_BUSY';
export const PUT_ERROR_OCCURRED = 'PUT_ERROR_OCCURRED';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGOUT = 'POST_LOGOUT';
export const GET_AUCTION_ITEMS = 'GET_AUCTION_ITEMS';
export const PUT_AUCTION_ITEM_DRAFT = 'PUT_AUCTION_ITEM_DRAFT';
